name: Publish
on:
  push:
    tags: ["*"]
    paths:
      - 'package.json'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Publish NPM
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '>=16.8.0'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          npm ci
          npm test
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


      - name: Publish GH Package
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '>=16.8.0'
          registry-url: https://npm.pkg.github.com/
          scope: "@heliomarpm"
      - run: npm ci
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
