name: Publish
on:
  push:
    tags: ["*"]
    paths:
      - 'package.json'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4


      # PUBLICANDO EM NPMJS
      - name: Setup Node NPM
        uses: actions/setup-node@v3
        with:
          node-version: '>=16.8.0'
          registry-url: https://registry.npmjs.org/
          scope: "@heliomarpm"

      - name: Install Dependencies
        run: npm ci

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Publish NPM Package
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


      # PUBLICANDO EM GITHUB PACKAGE
      - name: Setup Node GPR
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: "@heliomarpm"

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish GPR
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

